### ISSUE TITLE
Use default timezone when none found

### ISSUE THREAD

**Issue by rndstr** [eprbell/rp2#29]
I'm using a Google spreadsheet where I enter date formatted values and it seems it doesn't provide a timezone.

What about allowing to pass in a default timezone (CLI flag) that will be used when it cannot find one?

**Comment by rndstr** [comment]
A workaround I'm using locally is:

```
diff --git i/src/rp2/configuration.py w/src/rp2/configuration.py
index 0bc1fca..6d5aa05 100644
--- i/src/rp2/configuration.py
+++ w/src/rp2/configuration.py
@@ -13,7 +13,7 @@
 # limitations under the License.
 
 import json
-from datetime import date, datetime
+from datetime import date, datetime, timezone
 from pathlib import Path
 from typing import Any, Dict, List, Optional, Set
 
@@ -197,7 +197,7 @@ class Configuration:  # pylint: disable=too-many-public-methods
         except Exception as exc:
             raise RP2ValueError(f"Error parsing parameter '{name}': {str(exc)}") from exc
         if result.tzinfo is None:
-            raise RP2ValueError(f"Parameter '{name}' value has no timezone info: {value}")
+            result.replace(tzinfo=timezone.pt)
         return result
 
     def type_check_exchange(self, name: str, value: str) -> str:
```

**Comment by eprbell** [comment]
I hear you, but one of the design principles has been to avoid ambiguity as much as possible. I understand the use case, but I would prefer to remove the ambiguity in the original data, rather than feed RP2 timestamps without timezone. Based on what the above workaround does, it shouldn't be too hard to write a script that adds the time zone to your original spreadsheet.

**Comment by rndstr** [comment]
Makes sense, closing.
