### ISSUE TITLE
Feature Request - Open Positions / Unrealized Gains

### ISSUE THREAD

**Issue by mdavid217** [eprbell/rp2#32]
It'd be useful for me to see a table of open positions for all cryptos in a single table. Possible placement could be the summary tab or its own tab. 

The following fields alone would be quite handy: Asset, Exchange, Balance, Cost Basis of Position

It would be especially awesome if there was a field off to the side for "Current Spot Price" designated for the user to enter the current price of the asset, and additional calc fields near that for "Current Value", "Net Gain/Loss", "Pct Gain/Loss" which had the calculations already in place where once the spot price was entered, the corresponding values would be displayed.

There could be some finagling such that the user didn't have to enter the current spot value multiple times e.g. for the same asset held in multiple places, but that would be a minor inconvenience for the value provided.

**Comment by eprbell** [comment]
Interesting suggestion! I won't have time to work on this in the near future, but I'll review PRs if anybody wants to tackle this.

**Comment by dmac217** [comment]
I've started working on this as a new plugin. For now I have to put my templates into template_us.ods. Would it be reasonable to make the template file an argument, or would there be some better way to handle templates for plugins aside from adding to the vanilla template?

**Comment by eprbell** [comment]
Thanks for starting work on a new plugin! I like that this would go into a new plugin because this sounds more like investment management-related than tax-related, which is great, because RP2 can definitely provide more value than tax only.

Regarding the template: good question. I think each new plugins should have their own template files (except in special cases). This requires a small change to the `_initialize_output_file()` function (add the template parameter) and updates in the two call sites (in the two existing report plugins).

**Comment by mdavid217** [comment]
https://github.com/mdavid217/rp2/tree/openpositions

I have the report generating output I'm happy with. The pylint and mypy tests have a few failures which I'm not sure how to properly address in the tree. The branch also has the change to the ods generator to use a file with a specified prefix (sorta.. it prefixes it before country code, but keeps template in.) 

I wanted to outline the above before sending a PR as my experience with git has been to local repositories, and I'm not familiar with the PR process - wanted to avoid possibly creating a mess by doing a PR prematurely.

Comments / advise welcome.

**Comment by eprbell** [comment]
Great! I gave it a quick look, but it's a bit difficult to review stacked diffs: I suggest [going ahead with the PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), which is easier to read. And don't worry about messing anything up: the PR won't affect the main tree until we merge.

A few random notes from my rapid skimming of the code:
- if possible, always pass a string to RP2Decimal constructor: when using float you are losing precision.
- don't do `RP2Decimal(net_cost / tot_crypto_bal)`. Instead just use normal math operations with RP2Decimal objects: `net_cost / tot_crypto_bal` (assuming they are both RP2Decimal)
- to round to 2 decimals for Fiat: don't use round(). Instead (assuming you want to round and RP2Decimal called r): `r.quantize(FIAT_DECIMAL_MASK)`
- try to use descriptive identifiers for functions and variables: e.g instead of `ap_sheet`, `asset_price_sheet`

Looking forward to the PR!
