### ISSUE TITLE
Investment Expenses can no longer be used for Deductions

### ISSUE THREAD

**Issue by macanudo527** [eprbell/rp2#87]
It seems like according to the Tax Cuts and Jobs Act (TCJA) of 2017 itemized investment expenses can no longer be used. Form 4952 (https://www.irs.gov/pub/irs-pdf/f4952.pdf) can be used for Investment _Interest_ Deductions (like for margin trading) but not other expenses. The fees will need to be applied to the cost basis and deducted from the proceeds [according to this article](https://taxbit.com/cryptocurrency-tax-guide#how-can-investors-save-money-on-cryptocurrency-fees).  I think the `tax_report_us` report will need to be revised to reflect this, right?

**Comment by eprbell** [comment]
Trade fees are already applied to the transaction in RP2: buy fee adds to the cost bases and sell fee deducts from the proceeds, as the article describes (an example that is part of unit tests is input/test_data3.ods, sheet B1). Is there anything specifically that you think should change?

**Comment by macanudo527** [comment]
Ok, for some reason I got in my head that Investment Expenses were used for deductions after calculating capital gains. Maybe it's just my misunderstanding. So, the Investment Expenses tab in the US tax report is basically just there for information purposes only? or would this be used if I were operating a business?

I understand I should be consulting a tax accountant and DYOR and you are NFA.

**Comment by eprbell** [comment]
Got it, no, trading fees are already considered when computing capital gains (they affect cost basis and proceeds). The investment expenses tab contains two things currently (see https://github.com/eprbell/rp2/blob/main/src/rp2/plugin/report/us/tax_report_us.py#L57):
* transfer fee (the fee of move transaction);
* fee-only transactions.

As you mentioned, how to tax these and which forms to use is indeed a question for a CPA.

**Comment by macanudo527** [comment]
Oh, no. I've made an error with one of the plugins, then. For some reason, spot trading fees appear to be showing up in that tab.

**Comment by eprbell** [comment]
Are they Fee only transactions (transaction type == Fee)?

**Comment by macanudo527** [comment]
Yeah, I'll have to look at my code.

**Comment by macanudo527** [comment]
OK, I got it now. Pionex and Binance charge a fee in the crypto asset when purchasing it with USDT. The report generator is creating artifical transactions but these should actually be used for cost basis.

For example, I buy 1 BTC for $9000, and they charge a 0.1 BTC fee.
There should be a 0.9 BTC InTransaction. And the cost basis for that BTC should be $10000/BTC.   

However, right now the cost basis is $9000/BTC and a fee is generated to be used to reduce my capital gains. I think it all works out in the end, but it's not the correct accounting.

**Comment by eprbell** [comment]
Ah, yes, because it's a conversion, which is modeled as one in-transaction with crypto fee + one USDT out transaction. RP2 represents the in-transaction with crypto fee as 2 transactions in the output:
* one in-transaction (without crypto fee, but with fiat fee equivalent to the crypto fee)
* an artificial FEE transaction to model the crypto fee of the in-transaction (see https://github.com/eprbell/rp2/blob/main/src/rp2/ods_parser.py#L214). 

I think accounting is OK as-is, because the in-transaction has a fiat fee (equivalent to the crypto fee) which affects the cost basis as discussed above. The artificial FEE transaction is added only to capture the fact that some crypto went out to pay the fee (this affects the out flow of crypto). See test_data4.ods, sheet B1 as an example. Hope this helps.

**Comment by eprbell** [comment]
@macanudo527 is this issue resolved?

**Comment by eprbell** [comment]
Closing for now, but if you have more to add we'll reopen.
